In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
df = pd.read_csv("data.csv")

In [3]:
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [4]:
df.tail()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
564,926424,M,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,...,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115,NaN
565,926682,M,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,...,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637,NaN
566,926954,M,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,...,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820,NaN
567,927241,M,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,...,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400,NaN
568,92751,B,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,...,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039,NaN

In [5]:
df.shape

(569, 33)

In [6]:
df.columns

Index(['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst', 'Unnamed: 32'],
      dtype='object')

In [7]:
df.isnull().sum()

id                           0
diagnosis                    0
radius_mean                  0
texture_mean                 0
perimeter_mean               0
area_mean                    0
smoothness_mean              0
compactness_mean             0
concavity_mean               0
concave points_mean          0
symmetry_mean                0
fractal_dimension_mean       0
radius_se                    0
texture_se                   0
perimeter_se                 0
area_se                      0
smoothness_se                0
compactness_se               0
concavity_se                 0
concave points_se            0
symmetry_se                  0
fractal_dimension_se         0
radius_worst                 0
texture_worst                0
perimeter_worst              0
area_worst                   0
smoothness_worst             0
compactness_worst            0
concavity_worst              0
concave points_worst         0
symmetry_worst               0
fractal_dimension_worst      0
Unnamed: 32                569
dtype: int64

In [8]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [9]:
df.shape

(569, 31)

In [10]:
df.columns

Index(['diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst'],
      dtype='object')

In [11]:
df["diagnosis"].value_counts()

diagnosis
B    357
M    212
Name: count, dtype: int64

In [12]:
df["diagnosis"].map({"M":0,"B":1})

0      0
1      0
2      0
3      0
4      0
      ..
564    0
565    0
566    0
567    0
568    1
Name: diagnosis, Length: 569, dtype: int64

In [13]:
df["diagnosis"] = df["diagnosis"].map({"M":0,"B":1})

In [14]:
df["diagnosis"].value_counts()

diagnosis
1    357
0    212
Name: count, dtype: int64

In [15]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,0,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,0,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,0,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,0,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [16]:
X = df.drop(columns=["diagnosis"])
y = df["diagnosis"]

In [17]:
X.shape

(569, 30)

In [18]:
y.shape

(569,)

In [19]:
X.head

<bound method NDFrame.head of      radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
0          17.99         10.38          122.80     1001.0          0.11840
1          20.57         17.77          132.90     1326.0          0.08474
2          19.69         21.25          130.00     1203.0          0.10960
3          11.42         20.38           77.58      386.1          0.14250
4          20.29         14.34          135.10     1297.0          0.10030
..           ...           ...             ...        ...              ...
564        21.56         22.39          142.00     1479.0          0.11100
565        20.13         28.25          131.20     1261.0          0.09780
566        16.60         28.08          108.30      858.1          0.08455
567        20.60         29.33          140.10     1265.0          0.11780
568         7.76         24.54           47.92      181.0          0.05263

     compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
0             0.27760         0.30010              0.14710         0.2419
1             0.07864         0.08690              0.07017         0.1812
2             0.15990         0.19740              0.12790         0.2069
3             0.28390         0.24140              0.10520         0.2597
4             0.13280         0.19800              0.10430         0.1809
..                ...             ...                  ...            ...
564           0.11590         0.24390              0.13890         0.1726
565           0.10340         0.14400              0.09791         0.1752
566           0.10230         0.09251              0.05302         0.1590
567           0.27700         0.35140              0.15200         0.2397
568           0.04362         0.00000              0.00000         0.1587

     fractal_dimension_mean  ...  radius_worst  texture_worst  \
0                   0.07871  ...        25.380          17.33
1                   0.05667  ...        24.990          23.41
2                   0.05999  ...        23.570          25.53
3                   0.09744  ...        14.910          26.50
4                   0.05883  ...        22.540          16.67
..                      ...  ...           ...            ...
564                 0.05623  ...        25.450          26.40
565                 0.05533  ...        23.690          38.25
566                 0.05648  ...        18.980          34.12
567                 0.07016  ...        25.740          39.42
568                 0.05884  ...         9.456          30.37

     perimeter_worst  area_worst  smoothness_worst  compactness_worst  \
0             184.60      2019.0           0.16220            0.66560
1             158.80      1956.0           0.12380            0.18660
2             152.50      1709.0           0.14440            0.42450
3              98.87       567.7           0.20980            0.86630
4             152.20      1575.0           0.13740            0.20500
..               ...         ...               ...                ...
564           166.10      2027.0           0.14100            0.21130
565           155.00      1731.0           0.11660            0.19220
566           126.70      1124.0           0.11390            0.30940
567           184.60      1821.0           0.16500            0.86810
568            59.16       268.6           0.08996            0.06444

     concavity_worst  concave points_worst  symmetry_worst  \
0             0.7119                0.2654          0.4601
1             0.2416                0.1860          0.2750
2             0.4504                0.2430          0.3613
3             0.6869                0.2575          0.6638
4             0.4000                0.1625          0.2364
..               ...                   ...             ...
564           0.4107                0.2216          0.2060
565           0.3215                0.1628          0.2572
566           0.3403                0.1418          0.2218
567           0.9387                0.2650          0.4087
568           0.0000                0.0000          0.2871

     fractal_dimension_worst
0                    0.11890
1                    0.08902
2                    0.08758
3                    0.17300
4                    0.07678
..                       ...
564                  0.07115
565                  0.06637
566                  0.07820
567                  0.12400
568                  0.07039

[569 rows x 30 columns]>

In [20]:
y.head

<bound method NDFrame.head of 0      0
1      0
2      0
3      0
4      0
      ..
564    0
565    0
566    0
567    0
568    1
Name: diagnosis, Length: 569, dtype: int64>

In [21]:
from sklearn.model_selection import train_test_split

In [22]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

In [23]:
X_train.shape

(455, 30)

In [24]:
X_test.shape

(114, 30)

In [25]:
y_train.shape

(455,)

In [26]:
y_test.shape

(114,)

In [27]:
from sklearn.preprocessing import StandardScaler

In [28]:
scaler = StandardScaler()

In [29]:
scaler.fit(X_train)

StandardScaler()

In [30]:
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [31]:
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [32]:
X_train_scaled.shape

(455, 30)

In [33]:
X_test_scaled.shape

(114, 30)

In [34]:
from sklearn.linear_model import LogisticRegression

In [35]:
model = LogisticRegression()

In [36]:
model.fit(X_train_scaled, y_train)

LogisticRegression()

In [37]:
model.predict(X_test_scaled)

array([0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0,
       0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 1])

In [38]:
model.predict_proba(X_test_scaled)

array([[9.99999941e-01, 5.88824186e-08],
       [1.13351672e-05, 9.99988665e-01],
       [9.93589175e-01, 6.41082462e-03],
       [4.66491463e-01, 5.33508537e-01],
       [9.99999999e-01, 6.52500097e-10],
       [7.83960163e-03, 9.92160398e-01],
       [1.71746799e-05, 9.99982825e-01],
       [9.99999436e-01, 5.63527494e-07],
       [9.99945684e-01, 5.43163692e-05],
       [1.00000000e+00, 8.04184941e-11],
       [1.08214445e-02, 9.89178556e-01],
       [9.98667581e-01, 1.33241870e-03],
       [1.29622345e-03, 9.98703777e-01],
       [9.99973941e-01, 2.60592467e-05],
       [9.99723775e-01, 2.76224627e-04],
       [9.83676461e-02, 9.01632354e-01],
       [6.34138144e-01, 3.65861856e-01],
       [1.65002350e-01, 8.34997650e-01],
       [3.38813138e-05, 9.99966119e-01],
       [1.69826652e-02, 9.83017335e-01],
       [9.98342281e-01, 1.65771925e-03],
       [9.48260020e-01, 5.17399797e-02],
       [1.92114587e-04, 9.99807885e-01],
       [8.76676314e-04, 9.99123324e-01],
       [9.98978259e-03, 9.90010217e-01],
       [1.32531838e-01, 8.67468162e-01],
       [9.99999995e-01, 4.83595669e-09],
       [9.53621619e-03, 9.90463784e-01],
       [8.30118982e-04, 9.99169881e-01],
       [1.07783085e-03, 9.98922169e-01],
       [8.08702727e-03, 9.91912973e-01],
       [1.08571150e-05, 9.99989143e-01],
       [1.64726342e-02, 9.83527366e-01],
       [3.07609202e-02, 9.69239080e-01],
       [9.99994625e-01, 5.37502995e-06],
       [8.12010689e-01, 1.87989311e-01],
       [1.54859260e-03, 9.98451407e-01],
       [2.89466751e-02, 9.71053325e-01],
       [3.78737391e-01, 6.21262609e-01],
       [9.99994557e-01, 5.44264495e-06],
       [5.53594858e-05, 9.99944641e-01],
       [1.53270109e-04, 9.99846730e-01],
       [6.46331142e-03, 9.93536689e-01],
       [9.99999974e-01, 2.63830968e-08],
       [9.98287781e-01, 1.71221909e-03],
       [2.92781498e-01, 7.07218502e-01],
       [1.05607699e-06, 9.99998944e-01],
       [1.81419444e-04, 9.99818581e-01],
       [6.90893840e-02, 9.30910616e-01],
       [9.99730857e-01, 2.69142775e-04],
       [3.82982695e-04, 9.99617017e-01],
       [4.53361496e-01, 5.46638504e-01],
       [6.18947795e-04, 9.99381052e-01],
       [9.12718522e-02, 9.08728148e-01],
       [6.62002257e-02, 9.33799774e-01],
       [6.71776359e-04, 9.99328224e-01],
       [1.30038103e-05, 9.99986996e-01],
       [9.93850676e-01, 6.14932366e-03],
       [9.99999649e-01, 3.51063500e-07],
       [4.79983678e-02, 9.52001632e-01],
       [1.99288871e-03, 9.98007111e-01],
       [1.56388685e-05, 9.99984361e-01],
       [3.63594877e-04, 9.99636405e-01],
       [2.66694715e-02, 9.73330528e-01],
       [9.99993142e-01, 6.85828532e-06],
       [8.66864539e-01, 1.33135461e-01],
       [4.62954265e-01, 5.37045735e-01],
       [2.36267158e-03, 9.97637328e-01],
       [4.72684739e-02, 9.52731526e-01],
       [8.34118527e-02, 9.16588147e-01],
       [6.66005806e-04, 9.99333994e-01],
       [7.55636596e-03, 9.92443634e-01],
       [1.69123387e-06, 9.99998309e-01],
       [9.99894021e-01, 1.05978859e-04],
       [9.99515525e-01, 4.84475179e-04],
       [9.99958650e-01, 4.13497068e-05],
       [8.35820153e-01, 1.64179847e-01],
       [8.61616656e-04, 9.99138383e-01],
       [3.35793494e-04, 9.99664207e-01],
       [1.15336474e-02, 9.88466353e-01],
       [1.33850272e-01, 8.66149728e-01],
       [1.40742995e-04, 9.99859257e-01],
       [9.99995380e-01, 4.62039758e-06],
       [6.33163114e-05, 9.99936684e-01],
       [6.48119737e-01, 3.51880263e-01],
       [9.17280097e-04, 9.99082720e-01],
       [1.29599901e-02, 9.87040010e-01],
       [1.56141283e-05, 9.99984386e-01],
       [9.77363979e-02, 9.02263602e-01],
       [1.07194175e-01, 8.92805825e-01],
       [6.53688753e-02, 9.34631125e-01],
       [2.52976765e-02, 9.74702324e-01],
       [9.99999370e-01, 6.30292680e-07],
       [9.99864966e-01, 1.35034352e-04],
       [9.99533995e-01, 4.66005415e-04],
       [4.20125791e-07, 9.99999580e-01],
       [9.99970727e-01, 2.92733743e-05],
       [4.01950472e-03, 9.95980495e-01],
       [9.99999266e-01, 7.33955068e-07],
       [7.98082129e-03, 9.92019179e-01],
       [9.99498019e-01, 5.01981064e-04],
       [9.99999992e-01, 7.57868395e-09],
       [9.68276428e-01, 3.17235717e-02],
       [7.77601608e-03, 9.92223984e-01],
       [1.00000000e+00, 1.84406641e-13],
       [1.00000000e+00, 1.63299654e-23],
       [1.17168308e-03, 9.98828317e-01],
       [9.99965434e-01, 3.45656346e-05],
       [3.27326593e-04, 9.99672673e-01],
       [9.99998377e-01, 1.62311339e-06],
       [1.47954127e-01, 8.52045873e-01],
       [9.99377877e-01, 6.22123262e-04],
       [9.18002212e-02, 9.08199779e-01],
       [1.33119325e-02, 9.86688067e-01]])

In [39]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report