In [50]:
import pandas as pd
anime = pd.read_csv("anime.csv")
ratings = pd.read_csv("rating.csv")

anime.head()

,anime_id,name,genre,type,episodes,rating,members
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266

In [52]:
ratings.head()

   user_id  anime_id  rating
0        1        20      -1
1        1        24      -1
2        1        79      -1
3        1       226      -1
4        1       241      -1

In [53]:
anime.isnull().sum()

anime_id      0
name          0
genre        62
type         25
episodes      0
rating      230
members       0
dtype: int64

In [54]:
anime_clean = anime.copy()
ratings_clean = ratings.copy()

In [55]:
anime_clean["genre"] = anime_clean["genre"].fillna("Unknown")
anime_clean["type"] = anime_clean["type"].fillna("Unknown")
anime_clean["rating"] = anime_clean["rating"].fillna(anime_clean["rating"].median())

In [56]:
ratings_clean = ratings_clean[ratings_clean["rating"]!= -1]

In [58]:
anime_clean.isnull().sum()

anime_id    0
name        0
genre       0
type        0
episodes    0
rating      0
members     0
dtype: int64

In [59]:
ratings_clean.isnull().sum()

user_id     0
anime_id    0
rating      0
dtype: int64